/* 
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * OpenAPI spec version: 3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = EdFi.OdsApi.Sdk.Client.SwaggerDateConverter;

namespace EdFi.OdsApi.Sdk.Models.Profiles.Minnesota_TwentyTwo_TwentyThree_SISVendor_Profile
{
    /// <summary>
    /// MnSectionExtensionWritable
    /// </summary>
    [DataContract]
    public partial class MnSectionExtensionWritable :  IEquatable<MnSectionExtensionWritable>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MnSectionExtensionWritable" /> class.
        /// </summary>
        /// <param name="instructionalDeliveryModeDescriptor">The delivery mode of instuction. E.g, On-ground, Online, etc.</param>
        public MnSectionExtensionWritable(string instructionalDeliveryModeDescriptor = default(string))
        {
            this.InstructionalDeliveryModeDescriptor = instructionalDeliveryModeDescriptor;
        }
        
        /// <summary>
        /// The delivery mode of instuction. E.g, On-ground, Online, etc
        /// </summary>
        /// <value>The delivery mode of instuction. E.g, On-ground, Online, etc</value>
        [DataMember(Name="instructionalDeliveryModeDescriptor", EmitDefaultValue=false)]
        public string InstructionalDeliveryModeDescriptor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MnSectionExtensionWritable {\n");
            sb.Append("  InstructionalDeliveryModeDescriptor: ").Append(InstructionalDeliveryModeDescriptor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MnSectionExtensionWritable);
        }

        /// <summary>
        /// Returns true if MnSectionExtensionWritable instances are equal
        /// </summary>
        /// <param name="input">Instance of MnSectionExtensionWritable to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MnSectionExtensionWritable input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InstructionalDeliveryModeDescriptor == input.InstructionalDeliveryModeDescriptor ||
                    (this.InstructionalDeliveryModeDescriptor != null &&
                    this.InstructionalDeliveryModeDescriptor.Equals(input.InstructionalDeliveryModeDescriptor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InstructionalDeliveryModeDescriptor != null)
                    hashCode = hashCode * 59 + this.InstructionalDeliveryModeDescriptor.GetHashCode();
                return hashCode;
            }
        }
    }

}
